### * Get a single note

GET http://localhost:3001/api/notes/64107a55db5aed89b05c5220

### * Get all notes

GET http://localhost:3001/api/notes/

### * Delete a note

DELETE http://localhost:3001/api/notes/4

### * Create a new note

POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhYnlCYWNrUmlicyIsImlkIjoiNjQxZGJkYmUyOTYwOGE3ZDlhMDU3ODc5IiwiaWF0IjoxNjc5Njc1ODQxfQ.04uAN2bjv_CFZC4K1Xu39DNDSOmEBeMbaMAkWEHQygU

{
    "content": "I want to win! I deserve it!", 
    "important": false
}

### * Update a note

PUT http://localhost:3001/api/notes/6410ab578b0f4ef63b58da56
Content-Type: application/json

{
    "content": "Big Babby",
    "important": false
}
